language: php

php:
  - 5.4

sudo: false

cache:
  - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini || true
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0.0"
  - composer install --prefer-source --no-interaction
#  - app/yiic environment travis
  - php -S localhost:31415 -t web/ &

script: vendor/bin/codecept run

branches:
  only:
    - master